apiVersion: v1
kind: Secret
metadata:
  name: pay-as-you-go-consumer-jwt
  namespace: api-system
  labels:
    konghq.com/credential: jwt
stringData:
  algorithm: HS256
  secret: {{ .Values.pay_as_you_go_consumer.secret }} 
  key: {{ .Values.pay_as_you_go_consumer.key }}  
---
apiVersion: v1
kind: Secret
metadata:
  name: pay-as-you-go-consumer-acl
  namespace: api-system
  labels:
    konghq.com/credential: acl
stringData:
  group: pay-as-you-go-consumer
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: pay-as-you-go-consumer
  namespace: api-system
  annotations:
    kubernetes.io/ingress.class: kong
username: pay-as-you-go-consumer
credentials:
- pay-as-you-go-consumer-jwt
- pay-as-you-go-consumer-acl