apiVersion: v1
kind: Secret
metadata:
  name: plus-consumer-jwt
  namespace: api-system
  labels:
    konghq.com/credential: jwt
stringData:
  algorithm: HS256
  secret: {{ .Values.plus_consumer.secret }} 
  key: {{ .Values.plus_consumer.key }}  
---
apiVersion: v1
kind: Secret
metadata:
  name: plus-consumer-acl
  namespace: api-system
  labels:
    konghq.com/credential: acl
stringData:
  group: plus-consumer
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: plus-consumer
  namespace: api-system
  annotations:
    kubernetes.io/ingress.class: kong
username: plus-consumer
credentials:
- plus-consumer-jwt
- plus-consumer-acl