---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-stream-media
  labels:
    app: {{ .Release.Name }}-stream-media
  namespace: api-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-stream-media
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-stream-media
    spec:
      containers:
        - name: {{ .Release.Name }}-stream-media
          image: "{{ .Values.stream_media_image.repository }}:{{ .Values.stream_media_image.tag }}"
          imagePullPolicy: {{ .Values.stream_media_image.pullPolicy }}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stream-media-service
  labels:
    app: {{ .Release.Name }}-stream-media
  namespace: api-system
spec:
  selector:
    app: {{ .Release.Name }}-stream-media
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: stream-media-route
  namespace: api-system
  annotations:
    konghq.com/plugins: cors, jwt-auth, allow-premium
spec:
  parentRefs:
    - name: kong
      namespace: kong-system
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/stream-media
      backendRefs:
        - name: stream-media-service
          port: 8080
