apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: api-system
stringData:
  lago-api-key: {{ .Values.lago.api_key }}  
---
apiVersion: v1
kind: Secret
metadata:
  name: turn-secret
  namespace: api-system
stringData:
  turn-username: {{ .Values.turn_server.user }}  
  turn-password: {{ .Values.turn_server.password }}  