---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-stream-media
  labels:
    app: {{ .Release.Name }}-stream-media
  namespace: api-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-stream-media
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-stream-media
    spec:
      containers:
        - name: {{ .Release.Name }}-stream-media
          image: "{{ .Values.stream_media.repository }}:{{ .Values.stream_media.tag }}"
          imagePullPolicy: {{ .Values.stream_media.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
          - name: LAGO_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: lago-api-key 
          - name: TURN_USERNAME
            valueFrom:
              secretKeyRef:
                name: turn-secret
                key: turn-username 
          - name: TURN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: turn-secret
                key: turn-password
          command: {{ .Values.stream_media.command }}
          args: {{ .Values.stream_media.args }}
---
apiVersion: v1
kind: Service
metadata:
  name: stream-media-service
  labels:
    app: {{ .Release.Name }}-stream-media
  namespace: api-system
spec:
  selector:
    app: {{ .Release.Name }}-stream-media
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: stream-media-route
  namespace: api-system
  annotations:
    konghq.com/plugins: cors, jwt-auth, allow-premium
spec:
  parentRefs:
    - name: kong
      namespace: api-system
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/stream-media
      backendRefs:
        - name: stream-media-service
          port: 8080
