apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn-server
  namespace: api-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coturn-server
  template:
    metadata:
      labels:
        app: coturn-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: coturn
        image: coturn/coturn:latest
        ports:
        - containerPort: 3478
          protocol: UDP
          hostPort: 3478
        - containerPort: 3478
          protocol: TCP
          hostPort: 3478
        - containerPort: 5349
          protocol: UDP
          hostPort: 5349
        - containerPort: 5349
          protocol: TCP
          hostPort: 5349
        env:
        - name: TURN_USERNAME
          valueFrom:
            secretKeyRef:
              name: turn-secret
              key: turn-username 
        - name: TURN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: turn-secret
              key: turn-password 
        - name: EXTERNAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        command:
          - turnserver
          - -n
          - --log-file=stdout
          - --fingerprint
          - --lt-cred-mech
          - "--user=$(TURN_SERVER_USER):$(TURN_SERVER_PASSWORD)"
          - --realm=k8s.local
          - --min-port=49152
          - --max-port=49252
          - --verbose
---
apiVersion: v1
kind: Service
metadata:
  name: coturn-service
  namespace: api-system
spec:
  type: ClusterIP
  clusterIP: None 
  ports:
  - name: turn-udp
    port: 3478
    protocol: UDP
  - name: turn-tcp
    port: 3478
    protocol: TCP
  selector:
    app: coturn-server