apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors
  namespace: api-system
plugin: cors
config:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - OPTIONS 
  headers:
    - "*"
  credentials: false
