---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-normal-chat
  labels:
    app: {{ .Release.Name }}-normal-chat
  namespace: api-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-normal-chat
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-normal-chat
    spec:
      containers:
        - name: {{ .Release.Name }}-normal-chat
          image: "{{ .Values.normal_chat_image.repository }}:{{ .Values.normal_chat_image.tag }}"
          imagePullPolicy: {{ .Values.normal_chat_image.pullPolicy }}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: normal-chat-service
  labels:
    app: {{ .Release.Name }}-normal-chat
  namespace: api-system
spec:
  selector:
    app: {{ .Release.Name }}-normal-chat
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: normal-chat-route
  namespace: api-system
  annotations:
    konghq.com/plugins: cors, jwt-auth, allow-plus
spec:
  parentRefs:
    - name: kong
      namespace: kong-system
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/normal-chat
      backendRefs:
        - name: normal-chat-service
          port: 8080
